### ISSUE TITLE
Image flicker

### ISSUE THREAD

**Issue by filipandrei87** [rounak/RJImageLoader#4]
After the reveal animation is done, there is a quick flicker. Is there a way to remove this flicker?

**Comment by rounak** [comment]
yeah, I've noticed that a few times, but it doesn't appear consistently so I'm still trying to zero down on the issue.

**Comment by filipandrei87** [comment]
I notice it every time on an iPhone 6 device.
This also happens on the linked website's sample.

**Comment by ParsifalC** [comment]
the same issue.it's ok on the simulator,but there is a quick flicker on my iPhone6 every time.

**Comment by jbttn** [comment]
I have submitted pull request #5 which addresses this issue.

**Comment by ParsifalC** [comment]
thx.it works.@jbttn

**Comment by rounak** [comment]
Closing this.
